[package]
name = "interkern-rs"
version = "0.1.0"
authors = ["Alek Ratzloff <alekratz@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "*"
spin = "*"
multiboot2 = "*"
bitflags = "1"
x86_64 = "0.1.2"
